### ISSUE TITLE
Meta: make it easier for people to contribute to Bela as an open source project

### ISSUE THREAD

**Issue by jarmitage** [BelaPlatform/Bela#386]
Some ideas:
- [ ] Write a new main `README.md` that introduces the project, it's constituent parts, how it related to other repositories and how to contribute to it. It should be a README for developers as much as users.
- [ ] Specifically add a [contribution guide](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) to help people write clear issues and submit pull requests.
- [ ] Add new labels to issues that are community facing such as `Good first issue`. "This label marks tickets that are easy to get started with. The ticket should be ideal for beginners to dive into the code base." - http://docs.readthedocs.io/en/latest/issue-labels.html
- [ ] A clearer Wiki article bringing together development guides.
- [ ] A blog post outlining the above changes and describing developer workflow in a tutorial-like way.

**Comment by ConorShirren** [comment]
Hi @jarmitage - looking the contribute here and wondering if this issue is still required? I see you have a website published at  https://learn.bela.io/get-started-guide/ but the Docs within this repo seem pretty limited.
Thanks! 🙂

**Comment by giuliomoro** [comment]
Uff the imaginary associated with the word "meta" has changed significantly since the issue was opened ...

The get started guide and in general learn.bela.io are user-oriented and the vast majority of users wouldn't be interested in the development of the backend, which is what this issues is primarily about. Unfortunately we have done no significant process in addressing the issues above. It may be a catch-22 issue, but we also haven't seen a significant development effort from the community, as the small number of third-party PRs can testify. However, where possible we have provided feedback and attention to users willing to contribute, either publicly in the PR or forum or privately. The only thing that I feel the urge for right now is to have people make PRs against `dev` instead of `master`, not sure if there's a way to make that the default, without creating a contributing guide.

**Comment by jarmitage** [comment]
Hi @ConorShirren, quite an old issue you've stumbled across! As you can see there is still somewhat of a catch-22 here, as @giuliomoro says. However, I can testify that you will find Giulio and the Bela team responsive, helpful and generous with any queries you have. So I would perhaps suggest that you try to identify something specific you would like to contribute to, and create a thread on http://forum.bela.io if you need any help getting going.
